stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    outs:
      - data/raw/raw_data.csv


  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/raw_data.csv
    outs:
      - data/processed/processed_data.csv

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed/processed_data.csv
    params:
      - feature_engineering.test_size
    outs:
      - data/processed/train.csv
      - data/processed/test.csv


  model_building:
    cmd: python src/models/model_building.py
    deps:
      - src/models/model_building.py
      - data/processed/train.csv
    params:
      - model_building
    outs:
      - models/random_forest_model.pkl
